import type { Metadata } from "next";
import "./globals.css";
import Appbar from "@/components/Appbar";

import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import { WalletProvider } from "@/context/WalletContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import {Toaster} from "react-hot-toast"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(
          "min-h-screen  font-sans ",
          fontSans.variable
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <WalletProvider>
          <Toaster/>
          <Appbar/>
          {children}
        </WalletProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
